<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>TvMenu</AssemblyName>
    <Description>TvMenu Gorilla Tag Mod Menu</Description>
    <Version>1.2.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.0.8" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
  </ItemGroup>

  <Target Name="DownloadGameLibs" BeforeTargets="CoreCompile">
    <MakeDir Directories="Libs" />
    <DownloadFile SourceUrl="https://raw.githubusercontent.com/legoandmars/GorillaCosmetics/master/Libs/Assembly-CSharp.dll" DestinationFolder="Libs" Condition="!Exists('Libs/Assembly-CSharp.dll')" />
    <DownloadFile SourceUrl="https://raw.githubusercontent.com/legoandmars/GorillaCosmetics/master/Libs/PhotonUnityNetworking.dll" DestinationFolder="Libs" Condition="!Exists('Libs/PhotonUnityNetworking.dll')" />
    <DownloadFile SourceUrl="https://raw.githubusercontent.com/legoandmars/GorillaCosmetics/master/Libs/PhotonRealtime.dll" DestinationFolder="Libs" Condition="!Exists('Libs/PhotonRealtime.dll')" />
  </Target>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>Libs\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking">
      <HintPath>Libs\PhotonUnityNetworking.dll</HintPath>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>Libs\PhotonRealtime.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
