name: Build Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Download Game Dependencies
      run: |
        mkdir -p Libs
        curl -L -o repo.zip https://github.com/Atmospheric-Excursions/Gorilla-Tag-Modding-Template/archive/refs/heads/main.zip
        unzip repo.zip
        cp Gorilla-Tag-Modding-Template-main/Libs/*.dll Libs/
        rm -rf repo.zip Gorilla-Tag-Modding-Template-main

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Upload Artifact (.dll)
      uses: actions/upload-artifact@v4
      with:
        name: TvMenu
        path: bin/Release/netstandard2.1/*.dll
